### PR TITLE
Fix canChop(), remove canInteractWithRobot()

### LINKED ISSUE #332: canChop() does not match spec
canChop() is meant to take into account whether a robot has already attacked. Currently, it only takes into account whether the robot is a lumberjack, and the given tree is within range.

### LINKED ISSUE #333: Remove canInteractWithRobot()
This method seems like it's effectively useless, now that repairing has been removed.

### PR DESCRIPTION
**Pull request by nmccoy**
canChop() now checks for !hasAttacked().

Resolves #332 
Resolves #333

### CODE REVIEW

File: src/main/battlecode/world/RobotControllerImpl.java [hunk 1]
```diff
@@ -812,15 +812,15 @@ public boolean canChop(MapLocation loc) {
         boolean correctType = (getType() == RobotType.LUMBERJACK);
         boolean canInteract = canInteractWithTree(loc);
 
-        return correctType && canInteract;
+        return correctType && canInteract && !hasAttacked();
```
Comment (jbloxham) [inline src/main/battlecode/world/RobotControllerImpl.java]: A slightly better way of doing this might be to implement a paramater-less canChop() method, analogous to the parameter-less canShake() and canWater() methods.

Comment (nmccoy) [inline src/main/battlecode/world/RobotControllerImpl.java]: Chop counts as an attack though, so I believe this is proper form. shake() and water() have separate counts, so they have those parameter-less methods.
